name: Build DingoFS release
description: Build dingofs (Release) inside the dingo-eureka container and upload dingofs.tar.gz

runs:
  using: composite
  steps:
    - name: Copy dingofs repository
      shell: bash
      run: |
        echo "Move dingofs repository"
        sudo cp -r /home/runner/work/dingofs/dingofs /mnt/
        sudo chown $USER:$USER /mnt/dingofs

    - name: Configure Docker data-root
      shell: bash
      run: |
        sudo systemctl stop docker
        sudo systemctl stop docker.socket
        sudo mkdir -p /mnt/docker
        echo '{ "data-root": "/mnt/docker" }' | sudo tee /etc/docker/daemon.json
        if [ -d /var/lib/docker ]; then
          sudo mv /var/lib/docker /mnt/docker || true
        fi
        sudo systemctl start docker.socket
        sudo systemctl start docker
        docker info | grep "Docker Root Dir"
        echo "check disk space"
        df -h

    - name: Pull dingodatabase/dingo-eureka:rocky9-fs
      shell: bash
      run: |
        docker pull dingodatabase/dingo-eureka:rocky9-fs

    - name: Init build script
      shell: bash
      run: |
        cat <<EOF > /mnt/dingofs/build.sh
        #!/bin/bash
        set -x
        set -e

        cd / && git clone --branch main --single-branch https://github.com/dingodb/dingo-sdk.git && cd dingo-sdk && \
        git submodule sync --recursive && git submodule update --init --recursive && \
        mkdir build && cd build && cmake -DTHIRD_PARTY_INSTALL_PATH=/root/.local/dingo-eureka -DCMAKE_INSTALL_PREFIX=/root/.local/dingo-sdk -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SDK_EXAMPLE=OFF  -DBUILD_BENCHMARK=OFF -DBUILD_PYTHON_SDK=OFF -DBUILD_INTEGRATION_TESTS=OFF -DBUILD_UNIT_TESTS=OFF .. && \
        make -j16 && make install && export DINGOSDK_INSTALL_PATH=/root/.local/dingo-sdk

        cd /opt/dingofs/
        git config --global --add safe.directory /opt/dingofs

        make file_dep
        make file_build only=//src/* release=1 unit_tests=OFF
        # check if the build is successful
        if [ \$? -ne 0 ]
        then
            echo "build failed"
            exit -1
        fi
        make file_deploy_config
        # check install is successful
        if [ \$? -ne 0 ]
        then
            echo "install failed"
            exit -1
        fi

        tar -czvf dingofs.tar.gz -C scripts/docker/rocky9 dingofs
        # check size of tar file
        ls -lh dingofs.tar.gz

        echo "DingoFS Build finished"
        EOF
        chmod +x /mnt/dingofs/build.sh

    - name: Build DingoFS
      shell: bash
      run: |
        echo "Build DingoFS"
        docker run --name release-dingofs --rm -v /mnt/dingofs:/opt/dingofs/ dingodatabase/dingo-eureka:rocky9-fs /opt/dingofs/build.sh

    - name: Upload dingofs artifact
      uses: actions/upload-artifact@v4
      with:
        name: dingofs
        path: /mnt/dingofs/dingofs.tar.gz
        compression-level: 0
