{
 "title": "client",
 "description": "Dingofs client",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Addr",
    "query": {
     "query": "{__name__=~\"bthread_count\", job=\"client\"}"
    }
   },
   {
    "name": "fs",
    "label": "fsname",
    "query": {
     "query": "{__name__=~\"dingofs_s3_.*_adaptor_write_bps\", job=\"client\"}"
    }
   },
   {
    "name": "quantile",
    "label": "latency_quantile",
    "query": {
     "query": "{__name__=~\".*(latency_[0-9]*|latency)\", job=\"client\"}"
    }
   },
   {
    "name": "op",
    "label": "op",
    "query": {
     "query": "{__name__=~\"dingofs_fuse_op_.*_inflight_num\", job=\"client\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "process usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_memory_resident{instance=~\"$instance\"}",
       "legendFormat": "process_memory_resident {{instance}}"
      },
      {
       "expr": "process_memory_virtual{instance=~\"$instance\"}",
       "legendFormat": "process_memory_virtual {{instance}}"
      },
      {
       "expr": "process_memory_shared{instance=~\"$instance\"}",
       "legendFormat": "process_memory_shared {{instance}}"
      }
     ]
    },
    {
     "title": "process_cpu_usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_cpu_usage{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage {{instance}}"
      },
      {
       "expr": "process_cpu_usage_system{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage_system {{instance}}"
      },
      {
       "expr": "process_cpu_usage_user{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage_user {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "op latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "read_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_read_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_write_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "mkdir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 682 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_mkdir_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "rmdir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 682 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_rmdir_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "create_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 690 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_create_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "unlink_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 690 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_unlink_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "open_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 698 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_open_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "release_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 698 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_release_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "opendir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 706 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_opendir_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "releasedir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 706 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_releasedir_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "readdir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 714 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_readdir_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "readlink_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 714 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_readlink_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "lookup_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 722 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_lookup_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "mknod_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 722 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_mknod_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "link_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 730 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_link_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "symlink_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 730 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_symlink_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "getattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 738 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_getattr_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "setattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 738 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_setattr_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "getxattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 746 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_getxattr_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "listxattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 746 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_listxattr_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "fsync_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 754 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_fsync_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "flush_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 754 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_flush_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "rename_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 762 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_rename_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "op inflight number",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "op _inflight_num",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_[[op:regex]]_inflight_num\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "client interface performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "read_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_read_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_write_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_read_bps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_write_bps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_read_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_write_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_eps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_read_eps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_eps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_write_eps\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "diskcache r/w performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "read_diskcache_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 781 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_diskcache_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 781 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_diskcache_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 789 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_diskcache_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 789 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_diskcache_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 797 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_diskcache_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 797 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "block accesser performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "read_block_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_read_block_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_block_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_write_block_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_block_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_read_block_bps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_block_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_write_block_bps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_block_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_read_block_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_block_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_write_block_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "manager metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "file_manager_num",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_client_manager_file_manager_num\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "chunk_manager_num",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_client_manager_chunk_manager_num\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "diskcache  statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "cache blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_blocks\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "cache bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_bytes\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Stage Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_disk_cache_.*_stage_blocks\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cache misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_misses\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "cache hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_hits\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "mds client latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "mountfs_qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_mount_fs_qps\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "mountfs_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_mount_fs_lat_latency\", job=\"client\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "umountfs_qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_umount_fs_qps\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "umountfs_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_umount_fs_lat_latency\", job=\"client\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "get_fsinfo_qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_get_fs_info_qps\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "get_fsinfo_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_get_fs_info_lat_latency\", job=\"client\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "get_metaserver_info_qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_get_meta_server_info_qps\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "get_metaserver_info_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_get_meta_server_info_lat_latency\", job=\"client\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "get_metaserver_list_in_copysets_qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_get_meta_server_list_in_copysets_qps\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "get_metaserver_list_in_copysets_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_get_meta_server_list_in_copysets_lat_latency\", job=\"client\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "create_partition_qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_create_partition_qps\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "create_partition_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_create_partition_lat_latency\", job=\"client\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "get_copyset_of_partitions_qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_get_copyset_of_partitions_qps\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "get_copyset_of_partitions_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_get_copyset_of_partitions_lat_latency\", job=\"client\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "list_partition_qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_list_partition_qps\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "list_partition_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_list_partition_lat_latency\", job=\"client\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "alloc_s3_chunkid_qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_alloc_s3_chunk_id_qps\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "alloc_s3_chunkid_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_alloc_s3_chunk_id_lat_latency\", job=\"client\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "refresh_session_qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_refresh_session_qps\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "refresh_session_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_refresh_session_lat_latency\", job=\"client\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "get_latest_txid_qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_get_latest_tx_id_qps\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "get_latest_txid_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_get_latest_tx_id_lat_latency\", job=\"client\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "commit_tx_qps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_commit_tx_qps\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "commit_tx_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{__name__=~\"dingofs_mds_client_commit_tx_lat_latency\", job=\"client\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "metaserver client latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "create_inode_qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1474 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_create_inode_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "create_inode_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1474 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_create_inode_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "create_dentry_qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1480 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_create_dentry_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "create_dentry_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1480 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_create_dentry_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "get_inode_qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1486 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_get_inode_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "get_inode_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1486 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_get_inode_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "get_dentry_qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1492 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_get_dentry_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "get_dentry_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1492 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_get_dentry_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "list_dentry_qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1498 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_list_dentry_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "list_dentry_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1498 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_list_dentry_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "delete_dentry_qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1504 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_delete_dentry_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "delete_dentry_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1504 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_delete_dentry_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "delete_inode_qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1510 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_delete_inode_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "delete_inode_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1510 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_delete_inode_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "update_inode_qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1516 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_update_inode_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "update_inode_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1516 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_update_inode_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "batch_get_inodeattr_qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1522 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_batch_get_inode_attr_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "batch_get_inodeattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1522 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_batch_get_inode_attr_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "batch_get_xattr_qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1528 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_batch_get_xattr_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "batch_get_xattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1528 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_batch_get_xattr_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "append_s3_chunk_info_qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1534 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_append_s3_chunk_info_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "append_s3_chunk_info_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1534 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_append_s3_chunk_info_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "prepare_rename_tx_qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1540 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_prepare_rename_tx_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "prepare_rename_tx_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1540 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_metaserver_client_prepare_rename_tx_lat_latency\", job=\"client\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "warmup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "warmup_block_bps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "dingofs_warmup_block_cached_bps{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "warmup_block_qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "dingofs_warmup_block_cached_qps{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "warmup_block_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dingofs_warmup_block_cache_size{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}