{
 "title": "mdsv2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Addr",
    "query": {
     "query": "{__name__=~\"bthread_count\", job=\"mds\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "process usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "process memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_memory_resident{instance=~\"$instance\"}",
     "legendFormat": "process_memory_resident {{instance}}"
    },
    {
     "expr": "process_memory_virtual{instance=~\"$instance\"}",
     "legendFormat": "process_memory_virtual {{instance}}"
    },
    {
     "expr": "process_memory_shared{instance=~\"$instance\"}",
     "legendFormat": "process_memory_shared {{instance}}"
    }
   ]
  },
  {
   "title": "process cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage {{instance}}"
    },
    {
     "expr": "process_cpu_usage_system{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage_system {{instance}}"
    },
    {
     "expr": "process_cpu_usage_user{instance=~\"$instance\"}",
     "legendFormat": "process_cpu_usage_user {{instance}}"
    }
   ]
  },
  {
   "title": "service performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "mk_nod_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_mk_nod_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "mk_nod_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_mk_nod\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "mk_dir_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_mk_dir_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "mk_dir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_mk_dir\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "read_slice_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 250 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_read_slice_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "read_slice_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 250 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_read_slice\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "write_slice_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 258 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_write_slice_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "write_slice_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 258 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_write_slice\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "open_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 266 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_open_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "open_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 266 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_open\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "lookup_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 274 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_lookup_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "lookup_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 274 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_lookup\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "read_dir_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 282 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_read_dir_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "read_dir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 282 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_read_dir\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "read_link_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_read_link_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "read_link_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_read_link\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "get_inode_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_get_inode_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "get_inode_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_get_inode\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "batch_get_inode_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 306 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_batch_get_inode_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "batch_get_inode_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 306 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_batch_get_inode\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "get_dentry_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 314 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_get_dentry_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "get_dentry_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 314 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_get_dentry\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "list_dentry_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_list_dentry_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "list_dentry_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_list_dentry\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "rename_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 330 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_rename_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "rename_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 330 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_rename\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "rmdir_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 338 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_rm_dir_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "rmdir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 338 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_rm_dir\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "link_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 346 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_link_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "link_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 346 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_link\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "unlink_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 354 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_un_link_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "unlink_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 354 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_un_link\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "set_attr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 362 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_set_attr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "set_attr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 362 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_set_attr\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "set_xattr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 370 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_set_xattr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "set_xattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 370 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_set_xattr\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "get_attr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 378 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_get_attr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "get_attr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 378 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_get_attr\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "batch_get_xattr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_batch_get_xattr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "batch_get_xattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_batch_get_xattr\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "get_xattr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 394 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_get_xattr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "get_xattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 394 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_get_xattr\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "list_xattr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 402 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_list_xattr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "list_xattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 402 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_list_xattr\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "remove_xattr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 410 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_remove_xattr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "remove_xattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 410 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_remove_xattr\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fallocate_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 418 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_fallocate_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fallocate_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 418 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_fallocate\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "release_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 426 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_release_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "release_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 426 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_release\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "symlink_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 434 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_symlink_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "symlink_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 434 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_symlink\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "alloc_slice_id_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 442 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_alloc_slice_id_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "alloc_slice_id_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 442 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_alloc_slice_id\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "compact_chunk_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 450 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_compact_chunk_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "compact_chunk_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 450 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_compact_chunk\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "clean_trash_slice_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 458 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_clean_trash_slice_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "clean_trash_slice_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 458 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_clean_trash_slice\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "clean_del_file_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 466 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_clean_del_file_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "clean_del_file_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 466 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_clean_del_file\", job=\"mds\", instance=~\"$instance\",quantile=~\"avg\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "fs statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "mount_fs_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_mount_fs_count\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "mount_fs_error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_mount_fs_error\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "umount_fs_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_umount_fs_count\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "umount_fs_error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mdsv2_mdsservice_umount_fs_error\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}