{
 "title": "remotecache",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Cache Member: ",
    "query": {
     "query": "{__name__=~\"bthread_count\", job=\"remotecache\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "process usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_memory_resident{instance=~\"$instance\"}",
       "legendFormat": "process_memory_resident {{instance}}"
      },
      {
       "expr": "process_memory_virtual{instance=~\"$instance\"}",
       "legendFormat": "process_memory_virtual {{instance}}"
      },
      {
       "expr": "process_memory_shared{instance=~\"$instance\"}",
       "legendFormat": "process_memory_shared {{instance}}"
      }
     ]
    },
    {
     "title": "process cpu usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_cpu_usage{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage {{instance}}"
      },
      {
       "expr": "process_cpu_usage_system{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage_system {{instance}}"
      },
      {
       "expr": "process_cpu_usage_user{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage_user {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "cache hit statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "cache_hit_percent(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 474 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*\r\ndingofs_cache_hit_count{instance=~\"$instance\"}\r\n/\r\n(dingofs_cache_hit_count{instance=~\"$instance\"}+dingofs_cache_miss_count{instance=~\"$instance\"})\r\n>0\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cache_hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 474 },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_cache_hit_count\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cache_misses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 842 },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_cache_miss_count\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "diskcache group performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "load_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_load_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "load_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_load_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 227 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 227 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 235 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 235 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "load latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 243 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_load_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "load_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 243 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_load_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 251 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 251 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 259 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 259 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 267 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_blocks\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 267 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_bytes\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 275 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_stage_blocks\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cache_hit_percent(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 275 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * \r\nsum by (instance) (\r\n  {__name__=~\"dingofs_disk_cache_.*_cache_hits\",instance=~\"$instance\"}\r\n)\r\n/ \r\nsum by (instance) (\r\n {__name__=~\"dingofs_disk_cache_.*_cache_hits\",instance=~\"$instance\"} +\r\n {__name__=~\"dingofs_disk_cache_.*_cache_misses\",instance=~\"$instance\"}\r\n)\r\n> 0"
      }
     ]
    },
    {
     "title": "cache_hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 283 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_hits\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cache_misses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 283 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_misses\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "disk cache usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "disk_cache_group_capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (\r\n  {__name__=~\"dingofs_disk_cache_.*_capacity\", job=\"remotecache\"}\r\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "disk_capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_capacity\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk_cache_group_used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (\r\n  {__name__=~\"dingofs_disk_cache_.*_used_bytes\", job=\"remotecache\"}\r\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "disk_used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_used_bytes\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk_cache_group_used(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 *\r\nsum by (instance) (\r\n {__name__=~\"dingofs_disk_cache_.*_used_bytes\",job=\"remotecache\"}\r\n)\r\n/ \r\nsum by (instance) (\r\n  {__name__=~\"dingofs_disk_cache_.*_capacity\",job=\"remotecache\"}\r\n)\r\n> 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "disk_used(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * \r\n(\r\n  label_replace(\r\n    {__name__=~\"dingofs_disk_cache_(.*)_used_bytes\", job=\"remotecache\"},\r\n    \"disk_id\", \"$1\", \"__name__\", \"dingofs_disk_cache_(.+)_used_bytes\"\r\n  )\r\n /\r\n  label_replace(\r\n    {__name__=~\"dingofs_disk_cache_(.*)_capacity\", job=\"remotecache\"},\r\n    \"disk_id\", \"$1\", \"__name__\", \"dingofs_disk_cache_(.+)_capacity\"\r\n  )\r\n)\r\n> 0",
       "legendFormat": "{{instance}{disk_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "block accssser performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "read_block_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 444 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_read_block_bps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_block_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 444 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_write_block_bps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_block_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 452 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_read_block_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_block_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 452 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_write_block_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_block_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 460 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_read_block_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_block_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 460 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_write_block_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}