################################################# global
log_dir = "/tmp"
log_level = 0
access_logging = true

################################################# cache group node
[cache_group_node]
group_name = ""
listen_ip = "127.0.0.1"
listen_port = 9301
group_weight = 100
max_range_size_kb = 256
metadata_filepath = "/var/log/cache_group_meta"
load_members_interval_ms = 1000
local_access_enable = false
mds_addrs = ["127.0.0.1:6700"]

################################################# block cache
# { local block cache
[block_cache]
access_logging = true
cache_store = "disk"
stage_enable = false
cache_enable = false
upload_stage_throttle_enable = true
upload_stage_throttle_bandwidth_mb = 256
upload_stage_throttle_iops = 100
prefetch_max_inflights = 64

[block_cache.disk_cache]
# for cache management
cache_dir = [ '/var/run/dingofs' ]
cache_size_mb = [ 10240 ]
free_space_ratio = 0.1
cache_expire_s = 259200
cleanup_expire_interval_ms = 1000

# for IO
ioring_blksize = 1048576
ioring_iodepth = 128
ioring_prefetch = true
drop_page_cache = true

# for disk state
disk_state_tick_duration_s = 60
disk_state_normal2unstable_io_error_num = 3
disk_state_unstable2normal_io_succ_num = 10
disk_state_unstable2down_s = 1800
disk_state_disk_check_duration_ms = 3000
# }
