[server]
id = $INSTANCE_ID$
host = "$SERVER_HOST$" # can't set 0.0.0.0
listen_host = "$SERVER_LISTEN_HOST$" # maybe not set or set 0.0.0.0
port = $SERVER_PORT$


[server.service.meta]
read_worker_num = 128
read_worker_max_pending_num = 1024
read_worker_use_pthread = false

write_worker_num = 128
write_worker_max_pending_num = 1024
write_worker_use_pthread = false


[log]
level = "INFO"
path = "$BASE_PATH$/log"


[crontab]
heartbeat_interval_s = 5
fsinfosync_interval_s = 10
mdsmonitor_interval_s = 5
quota_sync_interval_s = 6
gc_interval_s = 30
