# global
[global]
access_logging = true
bthread_worker_num = 0

# fuse
[fuse]

[fuse.conn_info]
want_splice_move=false
want_splice_read=false
want_splice_write=false
want_auto_inval_data=true

[fuse.file_info]
direct_io=false
keep_cache=true

# vfs
[vfs]
cto = true
nocto_suffix = ""
max_name_length = 255
disable_xattr = true

[vfs.kernel_cache]
attr_timeout_s = 30
dir_attr_timeout_s = 30
entry_timeout_s = 30
dir_entry_timeout_s = 30

[vfs.lookup_cache]
negative_timeout_s = 0
min_uses = 1
lru_size = 100000

[vfs.dir_cache]
lru_size = 5000000

[vfs.attr_watcher]
lru_size = 5000000

[vfs.throttle]
avg_write_bytes = 0 # write
burst_write_bytes = 0
burst_write_bytes_s = 180
avg_write_iops = 0
burst_write_iops = 0
burst_write_iops_s = 180
avg_read_bytes = 0 # read
burst_read_bytes = 0
burst_read_bytes_s = 180
avg_read_iops = 0
burst_read_iops = 0
burst_read_iops_s = 180

# data
[meta]

[meta.v1.mds]

[meta.v1.metaserver]

[meta.v2.mds]
rpc_timeout_ms = 2000
rpc_retry_times = 3
client_send_request_retry_times = 3

# data
[data]

[data.background_flush]
interval_ms = 1000
trigger_force_memory_ratio = 0.90

[data.flush_file]
flush_workers = 10
flush_queue_size = 500

[data.flush_chunk]
flush_workers = 10
flush_queue_size = 500

[data.flush_slice]
flush_workers = 10
flush_queue_size = 500
stay_in_memory_max_s = 5

[data.page]
size = 65536
total_size_mb = 1024
use_pool = true

# rpc
[rpc]
defer_close_s = 1
health_check_interval_s = 0

[rpc.mds]
address = [ "127.0.0.1:6700" ]
retry_total_ms = 16000
rpc_timeout_ms = 2000

[rpc.metaserver]
max_retries = 10
max_internal_retries = 3
retry_interval_us = 100000
rpc_timeout_ms = 1000
rpc_stream_idle_timeout_ms = 500
batch_inode_attr_limit = 10000

# s3
[s3]

[s3.global]
log_level = 4
log_prefix = "/tmp/"
telemetry_enable = false

[s3.request]
region = "us-east-1"
use_virtual_addressing = false
verify_ssl = false
max_connections = 32
connect_timeout_ms = 60000
request_timeout_ms = 10000
use_crt_client = false
use_thread_pool = true
async_thread_num = true
max_async_request_inflight_bytes = 0

[s3.throttle]
iops_total_limit = 0
iops_read_limit = 0
iops_write_limit = 0
bps_total_mb = 0
bps_read_mb = 0
bps_write_mb = 0
