{
 "title": "client",
 "description": "Dingofs client",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Addr",
    "query": {
     "query": "{__name__=~\"bthread_count\", job=\"client\"}"
    }
   },
   {
    "name": "fs",
    "label": "fsname",
    "query": {
     "query": "{__name__=~\"dingofs_s3_.*_adaptor_write_bps\", job=\"client\"}"
    }
   },
   {
    "name": "quantile",
    "label": "latency_quantile",
    "query": {
     "query": "{__name__=~\".*(latency_[0-9]*|latency)\", job=\"client\"}"
    }
   },
   {
    "name": "op",
    "label": "op",
    "query": {
     "query": "{__name__=~\"dingofs_fuse_op_.*_inflight_num\", job=\"client\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cluster performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "cluster_read_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(dingofs_vfs_read_qps)", "legendFormat": "cluster read qps" }
     ]
    },
    {
     "title": "cluster_write_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(dingofs_vfs_write_qps)", "legendFormat": "cluster write qps" }
     ]
    },
    {
     "title": "cluster_read_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 489 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      { "expr": "sum(dingofs_vfs_read_bps)", "legendFormat": "cluster read bps" }
     ]
    },
    {
     "title": "cluster_write_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 489 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      { "expr": "sum(dingofs_vfs_write_bps)", "legendFormat": "cluster_write_bps" }
     ]
    }
   ]
  },
  {
   "title": "process usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_memory_resident{instance=~\"$instance\"}",
       "legendFormat": "process_memory_resident {{instance}}"
      },
      {
       "expr": "process_memory_virtual{instance=~\"$instance\"}",
       "legendFormat": "process_memory_virtual {{instance}}"
      },
      {
       "expr": "process_memory_shared{instance=~\"$instance\"}",
       "legendFormat": "process_memory_shared {{instance}}"
      }
     ]
    },
    {
     "title": "process_cpu_usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_cpu_usage{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage {{instance}}"
      },
      {
       "expr": "process_cpu_usage_system{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage_system {{instance}}"
      },
      {
       "expr": "process_cpu_usage_user{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage_user {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "op latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "read_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_read_lat_latency_(80|90)|dingofs_fuse_op_read_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_write_lat_latency_(80|90)|dingofs_fuse_op_write_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "mkdir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 291 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_mkdir_lat_latency_(80|90)|dingofs_fuse_op_mkdir_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "rmdir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 291 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_rmdir_lat_latency_(80|90)|dingofs_fuse_op_rmdir_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "create_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 299 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_create_lat_latency_(80|90)|dingofs_fuse_op_create_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "unlink_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 299 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_unlink_lat_latency_(80|90)|dingofs_fuse_op_unlink_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "open_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 307 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_open_lat_latency_(80|90)|dingofs_fuse_op_open_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "release_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 307 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_release_lat_latency_(80|90)|dingofs_fuse_op_release_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "opendir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 315 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_readdir_lat_latency_(80|90)|dingofs_fuse_op_opendir_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "releasedir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 315 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_releasedir_lat_latency_(80|90)|dingofs_fuse_op_releasedir_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "readdir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 323 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_readdir_lat_latency_(80|90)|dingofs_fuse_op_readdir_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "readlink_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 323 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_readlink_lat_latency_(80|90)|dingofs_fuse_op_readlink_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "lookup_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 331 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_lookup_lat_latency_(80|90)|dingofs_fuse_op_lookup_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "mknod_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 331 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_mknod_lat_latency_(80|90)|dingofs_fuse_op_mknod_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "link_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 339 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_link_lat_latency_(80|90)|dingofs_fuse_op_link_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "symlink_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 339 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_symlink_lat_latency_(80|90)|dingofs_fuse_op_symlink_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "getattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 347 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_getattr_lat_latency_(80|90)|dingofs_fuse_op_getattr_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "setattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 347 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_setattr_lat_latency_(80|90)|dingofs_fuse_op_setattr_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "getxattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 355 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_getxattr_lat_latency_(80|90)|dingofs_fuse_op_getxattr_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "listxattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 355 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_listxattr_lat_latency_(80|90)|dingofs_fuse_op_listxattr_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "fsync_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 363 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_fsync_lat_latency_(80|90)|dingofs_fuse_op_fsync_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "flush_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 363 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_flush_lat_latency_(80|90)|dingofs_fuse_op_flush_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "rename_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 371 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_rename_lat_latency_(80|90)|dingofs_fuse_op_rename_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "op inflight number",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "op _inflight_num",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_fuse_op_[[op:regex]]_inflight_num\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "client interface performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "read_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_read_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_write_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_read_bps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_write_bps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 189 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_read_lat_latency_(80|90)|dingofs_vfs_read_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 189 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_write_lat_latency_(80|90)|dingofs_vfs_write_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_eps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_read_eps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_eps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_vfs_write_eps\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "block accesser performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "read_block_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_read_block_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_block_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_write_block_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_block_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_read_block_bps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_block_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_write_block_bps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_block_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_read_block_lat_latency_(80|90)|dingofs_block_read_block_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_block_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_write_block_lat_latency_(80|90)|dingofs_block_write_block_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "diskcache group performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "load_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_load_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "load_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_load_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "load_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_load_lat_latency_(80|90)|dingofs_disk_cache_group_load_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "load_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_load_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_lat_latency_(80|90)|dingofs_disk_cache_group_stage_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_lat_latency_(80|90)|dingofs_disk_cache_group_cache_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_blocks\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_bytes\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_stage_blocks\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cache_hit_percent(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 *\r\nsum by (instance) (\r\n  {__name__=~\"dingofs_disk_cache_.*_cache_hits\",instance=~\"$instance\"}\r\n)\r\n/\r\nclamp_min(\r\n  sum by (instance) (\r\n {__name__=~\"dingofs_disk_cache_.*_cache_hits\",instance=~\"$instance\"} +\r\n    + {__name__=~\"dingofs_disk_cache_.*_cache_misses\",instance=~\"$instance\"}\r\n  ), 1\r\n)"
      }
     ]
    },
    {
     "title": "cache misses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_misses\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_hits\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "remote cache performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "load_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_range_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "load_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_range_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "load_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_range_lat_latency_(80|90)|dingofs_remote_node_group_range_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "load_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_range_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_put_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_put_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_put_lat_latency_(80|90)|dingofs_remote_node_group_put_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_put_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_cache_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_cache_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_cache_lat_latency_(80|90)|dingofs_remote_node_group_cache_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_cache_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "prefetch_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_prefetch_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "prefetch_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_prefetch_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "prefetch_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_prefetch_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "prefetch_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_node_group_prefetch_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "hit_ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_remote_cache_hit_ratio\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}