{
 "title": "mds",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Addr",
    "query": {
     "query": "{__name__=~\"bthread_count\", job=\"mds\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "online",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(up{job=~\"mds\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "offline",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(up{job=~\"mds\"})-sum(up{job=~\"mds\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "process usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 515 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_memory_resident{instance=~\"$instance\"}",
       "legendFormat": "process_memory_resident {{instance}}"
      },
      {
       "expr": "process_memory_virtual{instance=~\"$instance\"}",
       "legendFormat": "process_memory_virtual {{instance}}"
      },
      {
       "expr": "process_memory_shared{instance=~\"$instance\"}",
       "legendFormat": "process_memory_shared {{instance}}"
      }
     ]
    },
    {
     "title": "process cpu usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 515 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_cpu_usage{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage {{instance}}"
      },
      {
       "expr": "process_cpu_usage_system{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage_system {{instance}}"
      },
      {
       "expr": "process_cpu_usage_user{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage_user {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "service performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "mk_nod_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_mk_nod_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "mk_nod_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_mk_nod\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "mk_dir_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_mk_dir_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "mk_dir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_mk_dir\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "read_slice_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_read_slice_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "read_slice_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_read_slice\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "write_slice_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_write_slice_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "write_slice_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_write_slice\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "open_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_open_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "open_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_open\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "lookup_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_lookup_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "lookup_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_lookup\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "read_dir_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_read_dir_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "read_dir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_read_dir\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "read_link_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_read_link_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "read_link_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_read_link\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "get_inode_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_get_inode_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "get_inode_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_get_inode\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "batch_get_inode_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_batch_get_inode_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "batch_get_inode_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_batch_get_inode\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "get_dentry_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_get_dentry_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "get_dentry_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_get_dentry\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}\r\n",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "list_dentry_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_list_dentry_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "list_dentry_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_list_dentry\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "rename_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_rename_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "rename_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_rename\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "rmdir_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_rm_dir_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "rmdir_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_rm_dir\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "link_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_link_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "link_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_link\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "unlink_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_un_link_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "unlink_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_un_link\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "set_attr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_set_attr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "set_attr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_set_attr\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "set_xattr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_set_xattr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "set_xattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_set_xattr\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "get_attr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_get_attr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "get_attr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_get_attr\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "batch_get_xattr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_batch_get_xattr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "batch_get_xattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_batch_get_xattr\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "get_xattr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_get_xattr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "get_xattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_get_xattr\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "list_xattr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_list_xattr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "list_xattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_list_xattr\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "remove_xattr_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_remove_xattr_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "remove_xattr_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_remove_xattr\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "fallocate_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_fallocate_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fallocate_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_fallocate\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "release_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_release_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "release_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_release\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}\r\n",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "symlink_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_symlink_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "symlink_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_symlink\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "alloc_slice_id_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 211 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_alloc_slice_id_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "alloc_slice_id_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 211 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_alloc_slice_id\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "compact_chunk_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 219 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_compact_chunk_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "compact_chunk_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 219 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_compact_chunk\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "clean_trash_slice_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 227 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_clean_trash_slice_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "clean_trash_slice_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 227 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_clean_trash_slice\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "clean_del_file_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 235 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_clean_del_file_qps\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "clean_del_file_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 235 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_clean_del_file\", \r\n job=\"mds\", \r\n instance=~\"$instance\",\r\n quantile=~\"0\\\\.8|0\\\\.99|avg\"}",
       "legendFormat": "{{instance}}-latency-{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "fs statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "mount_fs_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 530 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_mount_fs_count\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "mount_fs_error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 530 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_mount_fs_error\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "umount_fs_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 546 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_umount_fs_count\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "umount_fs_error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 546 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\".*dingofs_pb_mds_mdsservice_umount_fs_error\",job=\"mds\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}