{
 "title": "remotecache",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Cache Member: ",
    "query": {
     "query": "{__name__=~\"bthread_count\", job=\"remotecache\"}"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "online",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(up{job=~\"remotecache\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "offline",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(up{job=~\"remotecache\"})-sum(up{job=~\"remotecache\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "process usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_memory_resident{instance=~\"$instance\"}",
       "legendFormat": "process_memory_resident {{instance}}"
      },
      {
       "expr": "process_memory_virtual{instance=~\"$instance\"}",
       "legendFormat": "process_memory_virtual {{instance}}"
      },
      {
       "expr": "process_memory_shared{instance=~\"$instance\"}",
       "legendFormat": "process_memory_shared {{instance}}"
      }
     ]
    },
    {
     "title": "process cpu usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_cpu_usage{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage {{instance}}"
      },
      {
       "expr": "process_cpu_usage_system{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage_system {{instance}}"
      },
      {
       "expr": "process_cpu_usage_user{instance=~\"$instance\"}",
       "legendFormat": "process_cpu_usage_user {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "cache hit statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "hit_ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*\r\ndingofs_cache_hit_count{instance=~\"$instance\"}\r\n/\r\n(dingofs_cache_hit_count{instance=~\"$instance\"}+dingofs_cache_miss_count{instance=~\"$instance\"})\r\n>0\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "diskcache group performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "load_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 259 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_load_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "load_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 259 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_load_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 323 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 323 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 331 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_bytes_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 331 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_op_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "load latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 339 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_load_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "load_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 339 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_load_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 347 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 347 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_cache_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 355 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 355 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_group_stage_error_per_second\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 363 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_blocks\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "cache_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 363 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_bytes\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "stage_blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 371 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_stage_blocks\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cache_hit_percent(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 371 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * \r\nsum by (instance) (\r\n  {__name__=~\"dingofs_disk_cache_.*_cache_hits\",instance=~\"$instance\"}\r\n)\r\n/ \r\nsum by (instance) (\r\n {__name__=~\"dingofs_disk_cache_.*_cache_hits\",instance=~\"$instance\"} +\r\n {__name__=~\"dingofs_disk_cache_.*_cache_misses\",instance=~\"$instance\"}\r\n)\r\n> 0"
      }
     ]
    },
    {
     "title": "cache_hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 379 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_hits\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cache_misses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 379 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_disk_cache_.*_cache_misses\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "disk cache usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "disk_cachegroup_statistics",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (\r\n  {__name__=~\"dingofs_disk_cache_.*_capacity\", job=\"remotecache\"}\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (instance) (\r\n  {__name__=~\"dingofs_disk_cache_.*_used_bytes\", job=\"remotecache\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "100*sum by (instance) (\r\n  {__name__=~\"dingofs_disk_cache_.*_used_bytes\", job=\"remotecache\"}\r\n)\r\n/\r\nclamp_min(\r\n  sum by (instance) (\r\n    {__name__=~\"dingofs_disk_cache_.*_capacity\", job=\"remotecache\"}\r\n  ), 1\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "block accssser performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "read_block_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_read_block_bps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_block_bps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_write_block_bps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_block_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_read_block_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_block_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_write_block_qps\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "read_block_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_read_block_lat_latency_(80|90)|dingofs_block_read_block_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "write_block_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "{__name__=~\"dingofs_block_write_block_lat_latency_(80|90)|dingofs_block_write_block_lat_latency\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}