
--mds_cluster_id=$CLUSTER_ID

# storage [dingo-store|tikv|dummy]
# storage_url depends on storage engine
# dingo-store: coordinator address
# tikv: pd address, example: list://10.220.32.42:2379
# dummy: no need address
# format: file://./conf/coor_list | list://ip1:port1,ip2:port2,... | ip1:port1,ip2:port2,...
--mds_storage_engine=$STORAGE_ENGINE
--storage_url=$STORAGE_URL

# server
--mds_server_id=$INSTANCE_ID
# can't set 0.0.0.0
--mds_server_host=$SERVER_HOST
# maybe not set or set 0.0.0.0
--mds_server_listen_host=$SERVER_LISTEN_HOST
--mds_server_port=$SERVER_PORT

# rdma
# --mds_use_rdma=false
# --rdma_device=bnxt_re0
# --rdma_port=1
# --rdma_gid_index=1
# --rdma_trace_verbose=true

# log
--log_dir=$BASE_PATH/log
--log_level=DEBUG
--log_v=0


# dingo-sdk
--rpc_channel_timeout_ms=30000
--rpc_channel_connect_timeout_ms=500
--rpc_time_out_ms=30000
# ts stale period(us)
--stale_period_us=1600
--tso_batch_size=512
--enable_rocksdb_perf_metric=true