[cache_group]
group_name = "default"
listen_ip = "127.0.0.1"
listen_port = 9302
group_weight = 100
max_range_size_kb = 256
metadata_filepath = "/var/log/cache_group_meta"
load_members_interval_ms = 1000

[block_cache]
logging = true
cache_store = "disk"
stage = true
stage_bandwidth_throttle_enable = false
stage_bandwidth_throttle_mb = 10240
upload_stage_workers = 10
upload_stage_queue_size = 10000
prefetch_workers = 128
prefetch_queue_size = 10000

[block_cache.disk_cache]
cache_dir = [ '/var/run/dingofs' ]
cache_size_mb = 10240
free_space_ratio = 0.1
cache_expire_s = 259200
cleanup_expire_interval_ms = 1000
drop_page_cache = true
ioring_iodepth = 128
ioring_blksize = 1048576
ioring_prefetch = true

[block_cache.disk_cache.disk_state]
tick_duration_s = 60
normal2unstable_io_error_num = 3
unstable2normal_io_succ_num = 10
unstable2down_s = 1800
disk_check_duration_ms = 3000
